# Generated by Django 6.0.2 on 2026-09-25 06:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisasterResponseTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('base_station', models.CharField(max_length=150)),
                ('commander_name', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(max_length=50)),
                ('readiness_level', models.CharField(default='HIGH_ALERT', max_length=50)),
                ('personnel_count', models.IntegerField(default=40)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('district', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(db_index=True, max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('elevation', models.FloatField(help_text='Elevation in meters above sea level')),
                ('slope', models.FloatField(help_text='Slope angle in degrees')),
                ('geology_code', models.IntegerField(default=4)),
                ('geology_description', models.CharField(default='Weathered Sandstone & Shale', max_length=150)),
                ('land_cover_code', models.IntegerField(default=1)),
                ('land_cover_description', models.CharField(default='Shrubland / Degraded Forest', max_length=150)),
                ('distance_to_fault_km', models.FloatField(default=5.0)),
                ('distance_to_road_cut_m', models.FloatField(default=50.0)),
                ('historical_landslides_count', models.IntegerField(default=0)),
                ('vulnerability_index', models.FloatField(default=0.5, help_text='0.0 to 1.0 composite baseline vulnerability')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['state', 'district', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LandslideIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_name', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('incident_date', models.DateField(db_index=True)),
                ('severity', models.CharField(choices=[('LOW', 'Low / Local Slump'), ('MODERATE', 'Moderate Debris Flow'), ('MAJOR', 'Major Highway Blockage / Structural Damage'), ('CATASTROPHIC', 'Catastrophic Mass Movement / Disaster')], default='MODERATE', max_length=20)),
                ('rainfall_amount_mm', models.FloatField(help_text='24h rainfall preceding landslide')),
                ('casualties', models.IntegerField(default=0)),
                ('injured', models.IntegerField(default=0)),
                ('road_blocked_days', models.FloatField(default=1.0)),
                ('estimated_damage_inr_lakhs', models.FloatField(default=15.0)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('trigger_type', models.CharField(default='Continuous Monsoonal Downpour', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='api.location')),
            ],
            options={
                'ordering': ['-incident_date'],
            },
        ),
        migrations.CreateModel(
            name='AlertNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_code', models.CharField(max_length=32, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk - Normal'), ('MEDIUM', 'Medium Risk - Watch'), ('HIGH', 'High Risk - Warning'), ('CRITICAL', 'Critical Risk - Emergency Alert')], default='HIGH', max_length=20)),
                ('risk_probability', models.FloatField()),
                ('rainfall_24h', models.FloatField()),
                ('rainfall_72h', models.FloatField(default=0.0)),
                ('soil_moisture', models.FloatField(default=80.0)),
                ('trigger_reason', models.TextField()),
                ('recommended_action', models.TextField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active Alert'), ('ACKNOWLEDGED', 'Acknowledged by Response Teams'), ('RESOLVED', 'Resolved / Downgraded')], db_index=True, default='ACTIVE', max_length=20)),
                ('channels_dispatched', models.CharField(default='Web Dashboard, SMS, Email, NDRF Alert Network', max_length=255)),
                ('recipients_notified', models.IntegerField(default=48)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('acknowledged_by', models.CharField(blank=True, max_length=150, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='api.location')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('rainfall_1h', models.FloatField(default=0.0)),
                ('rainfall_24h', models.FloatField(default=0.0)),
                ('rainfall_72h', models.FloatField(default=0.0)),
                ('soil_moisture', models.FloatField(default=45.0, help_text='Soil volumetric water content %')),
                ('temperature', models.FloatField(default=22.0, help_text='Temperature in Celsius')),
                ('humidity', models.FloatField(default=75.0, help_text='Relative humidity %')),
                ('pore_water_pressure_kpa', models.FloatField(default=12.5, help_text='Pore water pressure in kPa')),
                ('tilt_displacement_mm', models.FloatField(default=0.2, help_text='Subsurface tilt displacement in mm')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='api.location')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
