# Generated by Django 6.0.2 on 2026-09-25 07:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_name', models.CharField(default='Anonymous Resident', max_length=100)),
                ('reporter_phone', models.CharField(blank=True, default='', max_length=30)),
                ('incident_type', models.CharField(choices=[('ROAD_CRACK', 'Road / Pavement Tension Crack'), ('SOIL_SLUMP', 'Soil Subsidence / Ground Slumping'), ('ROCKFALL', 'Rockfall / Boulders on Highway'), ('WATER_SEEPAGE', 'Muddy Water Seepage from Slope'), ('ACTIVE_LANDSLIDE', 'Active Landslide / Debris Flow')], default='ROAD_CRACK', max_length=30)),
                ('location_name', models.CharField(max_length=150)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('description', models.TextField()),
                ('photo_url', models.CharField(blank=True, default='', max_length=500)),
                ('ai_vision_findings', models.TextField(blank=True, default='AI Vision analysis completed.')),
                ('ai_risk_score', models.FloatField(default=75.0)),
                ('ai_severity', models.CharField(default='HIGH', max_length=20)),
                ('ai_confidence', models.FloatField(default=92.5)),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Verification'), ('VERIFIED_DISPATCHED', 'Verified & Response Dispatched'), ('RESOLVED', 'Resolved & Hazard Cleared'), ('REJECTED', 'False Alarm / Duplicate')], db_index=True, default='PENDING_REVIEW', max_length=30)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('reviewed_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('facility_type', models.CharField(choices=[('HOSPITAL', 'Civil Hospital / Trauma Center'), ('SHELTER', 'Disaster Relief Shelter'), ('NDRF_CAMP', 'NDRF / SDRF Staging Base'), ('POLICE_HQ', 'District Police Headquarters'), ('FIRE_STATION', 'Fire & Emergency Rescue Station')], default='HOSPITAL', max_length=30)),
                ('state', models.CharField(db_index=True, max_length=100)),
                ('district', models.CharField(db_index=True, max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('capacity', models.IntegerField(default=100, help_text='Beds or personnel capacity')),
                ('emergency_phone', models.CharField(max_length=50)),
                ('status', models.CharField(default='OPERATIONAL', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SafeEvacuationRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('origin_area', models.CharField(max_length=150)),
                ('distance_km', models.FloatField(default=12.5)),
                ('estimated_time_mins', models.IntegerField(default=25)),
                ('safety_status', models.CharField(default='RECOMMENDED_SAFE', max_length=30)),
                ('hazard_road_status', models.CharField(default='BLOCKED_HIGH_RISK', max_length=30)),
                ('safe_waypoints_json', models.TextField(help_text='JSON list of [lat, lng] for safe green route')),
                ('hazard_waypoints_json', models.TextField(help_text='JSON list of [lat, lng] for red blocked road')),
                ('advisory_notes', models.TextField(blank=True)),
                ('destination_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evacuation_routes', to='api.emergencyfacility')),
            ],
        ),
    ]
